Update setting_up.md
rust-qt/rust-qt.github.io pull request #2
Opened 2020-06-13 19:15 UTC by mhavrlent

* replaced form1 with basic_form as form1 doesn't exist anymore
* added hint for msys2 users on one of the most common issues

2020-06-16 21:01 UTC, Riateche requested changes
Thank you for the contribution! This seems helpful. There are small changes I would like to make (see the review).

2020-06-16 21:01 UTC, Riateche commented on content/qt/setting_up.md
> +MSYS2 users:
If it's intended to be a header, it should be formatted as a header. However, I think it's better to just make it a part of the next sentence: "It you use MSYS2 and you get the following error..."

2020-06-16 21:01 UTC, Riateche commented on content/qt/setting_up.md
> +If you'll get following error: "The procedure entry point inflateValidate could not be located in the dynamic link library C:\msys64\mingw64\bin\libpng16-16.dll", it's usually caused by some other zl
"If you'll get" -> "If you get".

2020-06-16 21:01 UTC, Riateche commented on content/qt/setting_up.md
> +You can verify this from msys2 shell using following commmand:
"msys2 shell" -> "MSYS2 shell". "using following commmand" -> "using the following commmand".

The line break between "PATH." and "You" should be removed, as it doesn't affect the rendering.

2020-06-16 21:01 UTC, Riateche commented on content/qt/setting_up.md
> +If you'll get following error: "The procedure entry point inflateValidate could not be located in the dynamic link library C:\msys64\mingw64\bin\libpng16-16.dll", it's usually caused by some other zl
"following error" -> "the following error"

2020-06-16 21:01 UTC, Riateche commented on content/qt/setting_up.md
> +To fix this, you either need to fix your PATH or copy zlib1.dll from your "C:\msys64\mingw64\bin" directory to your "target\debug" and "target\release" directory.
"directory" -> "directories".

All paths, file names, and identifiers should be formatted using backticks (`) instead of quotes (").

2020-06-20 16:57 UTC, mhavrlent commented
@Riateche 
I've made the changes you requested. Please do the review.

2020-06-20 23:26 UTC, merged

2020-06-20 23:29 UTC, Riateche commented
Thank you.